### ISSUE TITLE
How test a service code coverage?

### ISSUE THREAD

**Issue by painsAgains** [codingsoo/REST_Go#4]
Sorry to bother you,
 In the paper 

> Automated Test Generation for REST APIs: No Time to Rest Yet

 I observed that the experimental metrics you selected include code coverage, I would like to ask you how to detect the code coverage of a RESTAPI Fuzz tool under a particular service in general?

Because the purpose of the selected black box is due to the lack of access to the source code, then for some black box tools is it necessary to test the code coverage?
Looking forward to your reply，
Thanks

**Comment by codingsoo** [comment]
Hi painsAgains,

Thank you for reaching out. The way that measures achieved code coverage depends on the programming language that a RESTful service used. Since we only used Java-based services, we used Jacoco.

Measuring code coverage can be unnecessary, but achieved code coverage can help you understand how much of your source is tested. Also, our paper found a strong correlation between achieved code coverage and the number of found bugs.
